
## A demo robot with a few AIOS actuators. Listed parameters are mandatory for an AIOS robot.
AIOSDUMMY:
  networkIP: "10.10.10.255" #Brodacast IP of AIOS actuators network
  nbJoints: 0 #Should match number of entries in the following list
  jointIDs: [] # ["C012D5549434", "2C76D5549434"] #Expected actuators IDs IN CORC EXPECTED ORDER
  jointNames: [] #["RHipExt", "RKnee"]
  qSigns: [] #[-1, -1]
  qCalibration: [] #[35, 0] #Joint position in degree at calibration pose (i.e. on stop)

EXO22:
  networkIP: "10.10.10.255" #Brodacast IP of AIOS actuators network
  nbJoints: 6 #Should match number of entries in the following list
  jointIDs: ["C012D5549434", "64A0D5549434", "9080D5549434", "C4D9D4549434", "0842D4549434", "4090D5549434"] #Expected actuators IDs IN CORC EXPECTED ORDER
  jointNames: ["LHipAbd", "RHipAbd", "LHipExt", "RHipExt", "LKnee", "RKnee"]
  qSigns: [1, -1, 1, -1, -1, 1] # ISB Standard: +ve Hip Adduction, +ve Hip Flexion, +ve Knee Flexion
  qCalibration: [-25, -25, -20, -20, 0, 0] #Joint position in degree at calibration pose (i.e. on stop)
  calibrationDirection: [-1, -1, -1, -1, -1, -1] # Direction to move for calibration pose
  qLimits: [-25, 15, -25, 15, -20, 125, -20, 125, 0, 120, 0, 120] # Joints limits (in deg) {q1_min, q1_max, ..., qN_min, qN_max}
  dqMax: 50 #Max allowable speed for every joint (deg/s)
  tauMax: 0.5 #Max allowable torque for every joint (internal unit)

AIOSDEMO:
  networkIP: "10.10.10.255" #Brodacast IP of AIOS actuators network
  nbJoints: 2 #Should match number of entries in the following list
  jointIDs: ["C4D9D4549434", "64A0D5549434"] #Expected actuators IDs IN CORC EXPECTED ORDER
  jointNames: ["RHipExt", "RKnee"]
  qSigns: [-1, 1]
  qCalibration: [125, 120] #Joint position in degree at calibration pose (i.e. on stop)
  qLimits: [-18, 123, 2, 118] # Joints limits (in deg) {q1_min, q1_max, ..., qN_min, qN_max}
  dqMax: 25 #Max allowable speed for every joint (deg/s)
  tauMax: 0.5 #Max allowable torque for every joint (internal unit)
  
AIOS1DOF:
  networkIP: "10.10.10.255" #Brodacast IP of AIOS actuators network
  nbJoints: 1 #Should match number of entries in the following list
  jointIDs: ["64A0D5549434"] #Expected actuators IDs IN CORC EXPECTED ORDER
  jointNames: ["Knee"]
  qSigns: [1]
  qCalibration: [120] #Joint position in degree at calibration pose (i.e. on stop)
  qLimits: [5, 120] # Joints limits (in deg) {q1_min, q1_max, ..., qN_min, qN_max}
  dqMax: 25 #Max allowable speed for every joint (deg/s)
  tauMax: 0.5 #Max allowable torque for every joint (internal unit)
  
