
## A demo robot with a few AIOS actuators. Listed parameters are mandatory for an AIOS robot.
AIOSDEMO:
  networkIP: "10.10.10.255" #Brodacast IP of AIOS actuators network
  nbJoints: 2 #Should match number of entries in the following list
  jointIDs: ["C4D9D4549434", "64A0D5549434"] #Expected actuators IDs IN CORC EXPECTED ORDER
  jointNames: ["RHipExt", "RKnee"]
  qSigns: [-1, 1]
  qCalibration: [125, 120] #Joint position in degree at calibration pose (i.e. on stop)
  qLimits: [-18, 123, 2, 118] # Joints limits (in deg) {q1_min, q1_max, ..., qN_min, qN_max}
  dqMax: 25 #Max allowable speed for every joint (deg/s)
  tauMax: 0.5 #Max allowable torque for every joint (internal unit)

  
AIOS1DOF:
  networkIP: "10.10.10.255" #Brodacast IP of AIOS actuators network
  nbJoints: 1 #Should match number of entries in the following list
  jointIDs: ["64A0D5549434"] #Expected actuators IDs IN CORC EXPECTED ORDER
  jointNames: ["Knee"]
  qSigns: [1]
  qCalibration: [120] #Joint position in degree at calibration pose (i.e. on stop)
  qLimits: [5, 120] # Joints limits (in deg) {q1_min, q1_max, ..., qN_min, qN_max}
  dqMax: 25 #Max allowable speed for every joint (deg/s)
  tauMax: 0.5 #Max allowable torque for every joint (internal unit)
  
